### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CarlosUziel** [mah51/michael-hall.me#17]
Hi @mah51,

Right now this repository lacks a license, which means that nobody can use this source code without explicit permission. I wanted to know if this was an oversight or was intentional, as I would love to use this site as a starting point for my own personal portfolio.

In case you need it,  GitHub also offers  documentation about licenses. You can find it [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

Thanks in advance!

**Comment by mah51** [comment]
Hey thanks for asking! I am more than happy for you to use this project, I have added an MIT License which allows free use i think. Good luck making your website, and if you make any improvements don't keep them to yourself 😠. Im just kidding but any suggestions are welcome!

**Comment by CarlosUziel** [comment]
Thank you very much! I just made my website repository public (https://github.com/CarlosUziel/carlosuziel.pm), and the website itself is freshly deployed too (https://carlosuziel-pm.vercel.app/), though I am still testing it.

I am quite new to web development so I pretty much streamlined and simplified most of your codebase to adapt it to my needs, and it was _almost always_ easy to understand what part of your code was doing what. 

I think one of the things I really didn't like was that the footer was always hidden unless you scrolled down a bit, because the main div had a height of `100vh`, I changed it slightly so that the footer would always be at the end of the page if the content allowed for it.

**Comment by mah51** [comment]
Wow, that looks great! I'm glad you managed to create something original and unique from my project! Im also pleased to hear you didn't have a hard time understanding my code, but im sure there will be something that I have messed up so feel free to leave an issue if you struggle with something. 

An issue I noticed on my phone is the small project cards on the project page arent at the height they are meant to be so you cant read anything on them, however when I went onto my computer and shrunk the window to the size of an iPhone 6 I didn't have this problem so maybe that's something to look into, and if you have any issues I'd be glad to help. (Its probably some weird styling issue, css is weird like that).

Also I briefly looked at your masters paper on using CNNs to identify stroke lesions in perfusion MRI scans and it looks really interesting. I will have to read it sometime this week! This year I am doing my masters in computational biology too, and will be attempting to identify protein function of small proteins with a neural net, so I know who to come to if I am stuck :D.

**Comment by CarlosUziel** [comment]
> An issue I noticed on my phone is the small project cards on the project page arent at the height they are meant to be so you cant read anything on them, however when I went onto my computer and shrunk the window to the size of an iPhone 6 I didn't have this problem so maybe that's something to look into, and if you have any issues I'd be glad to help. (Its probably some weird styling issue, css is weird like that).

Maybe it's an issue with the browser you are using on your phone? I liked a lot the backdrop-filter you used in some parts of your site, so I ended up using it in lots of places. Then I realized that the latest version of Firefox still doesn't support it, so some parts look wonky on Firefox.

> Also I briefly looked at your masters paper on using CNNs to identify stroke lesions in perfusion MRI scans and it looks really interesting. I will have to read it sometime this week!

Thank you! I appreciate it. Though the paper is quite old already so there's probably newer stuff and hopefully new algorithms that improved the performance of the one I discuss in the paper.

> This year I am doing my masters in computational biology too, and will be attempting to identify protein function of small proteins with a neural net, so I know who to come to if I am stuck :D.

That sounds awesome! Actually I am in my second year of my PhD in Computational Biology, also working with a very specific protein for Prostate Cancer. If you are going to work with sequencing data, I truly believe that Graph Neural Networks are the way to go.

**Let's keep in contact! You should be able to see my email on my profile when logged in here on GitHub.**
