### ISSUE TITLE
I install '@chakra-ui/react' from chakra official site, but it's not solve yet 

### ISSUE THREAD

**Issue by SANKARAMDAS** [mah51/michael-hall.me#26]
![2022-03-01 (1)](https://user-images.githubusercontent.com/31897843/156051551-32aacaca-12de-4a71-89f9-177a95ab0930.png)
![2022-03-01](https://user-images.githubusercontent.com/31897843/156051556-9c9b5c71-bf50-48a0-bab0-a2f1cc451ee9.png)

I tried to solve it through -  npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4
 npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^5   

nut unable to rectify the prob yet.

**Comment by mah51** [comment]
Hmm... This could simply be a problem with the typescript interpreter. Try running npm run dev and see if it starts. Additionally try pressing CTRL + SHIFT + P (windows) or CMD + SHIFT + P (mac) and typing in restart ts server and hitting enter, sometimes I find it needs a restart after installing a package or two.

**Comment by mah51** [comment]
Also just running `npm install` in that directory should install all the dependencies by itself

**Comment by SANKARAMDAS** [comment]
npm run dev- this works for me.  Thanks man.
